### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by boomzero** [langningchen/math#3]
<img width="1392" alt="image" src="https://github.com/langningchen/math/assets/85378277/e30d5f81-0b13-4ce7-9de3-09fc4c9246af">

**Comment by langningchen** [comment]
......

**Comment by langningchen** [comment]
按理说虚数应该也是支持的

**Comment by langningchen** [comment]
好像确实不行

**Comment by langningchen** [comment]
![Screenshot_20240202_165121](https://github.com/langningchen/math/assets/81672884/9d9056f2-0b06-440e-b258-fbe6ee0da006)
Microsoft Math Solver本来就不支持，所以你应该向他提Issue而并不是我这里

**Comment by boomzero** [comment]
应显示无解
