### ISSUE TITLE
cannot use in dark mode

### ISSUE THREAD

**Issue by boomzero** [langningchen/math#4]
<img width="1370" alt="image" src="https://github.com/langningchen/math/assets/85378277/c978d49f-1d8f-461d-9692-5f820ac4bf36">

**Comment by langningchen** [comment]
？
![image](https://github.com/langningchen/math/assets/81672884/f7fd8f0c-4abb-46a3-b824-be47488c58f6)

**Comment by langningchen** [comment]
Seems well to me

**Comment by langningchen** [comment]
May be a bug to the dependency: https://github.com/arnog/mathlive

**Comment by langningchen** [comment]
~说句闲话，你有没有发现我的代码在做unpkg的代理~

**Comment by boomzero** [comment]
> ~说句闲话，你有没有发现我的代码在做unpkg的代理~

什么意思

**Comment by langningchen** [comment]
> 什么意思

![image](https://github.com/langningchen/math/assets/81672884/f9ce307c-713d-4770-815a-c3af1cfe3d8e)
访问 `https://math.chenlangning.me/mathlive/dist/mathlive.min.js` 返回的是 `https://unpkg.com/mathlive/dist/mathlive.min.js` 的内容

**Comment by langningchen** [comment]
https://github.com/langningchen/math/blob/af0b9f610d7b0eed5ca999b5bf600e35e322411d/Source/index.ts#L101-L107

**Comment by boomzero** [comment]
@langningchen this is a real bug, so

**Comment by langningchen** [comment]
@boomzero I can't reproduce

**Comment by langningchen** [comment]
I'v said that it may be a bug of my dependency

**Comment by boomzero** [comment]
Well you should probably file a bug in the upstream repository发自我的 iPhone在 2024年2月11日，13:15，Langning Chen ***@***.***> 写道：﻿
I'v said that it may be a bug of my dependency

**Comment by boomzero** [comment]
> @boomzero I can't reproduce

@langningchen  good luck getting this Github achievement!

![qwq](https://github.com/langningchen/math/assets/85378277/3c67f65c-b04f-44c8-bf64-38b9a750037d)

**Comment by langningchen** [comment]
Emm
